services:
  - type: web
    name: reposteria-djuancito
    env: docker
    branch: main
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
      - key: JWT_SECRET
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
